//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicBookGallery.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDER_DETAIL
    {
        public string Order_Number { get; set; }
        public string Line_Number { get; set; }
        public string Part_Number { get; set; }
        public string Sec_Part_Number { get; set; }
        public string Lot_Number { get; set; }
        public string User_Field { get; set; }
        public int Order_Quantity { get; set; }
        public int Alloc_Quantity { get; set; }
        public int Picked_Quantity { get; set; }
        public Nullable<System.DateTime> Completed_Date { get; set; }
        public Nullable<System.DateTime> Uploaded_Date { get; set; }
        public bool Uploaded_Flag { get; set; }
        public string User_Name { get; set; }
        public Nullable<int> Download_Rec_Identity { get; set; }
    }
}
